version: '2'

services:
#  postgresql:
#    image: sameersbn/postgresql:14-20230628
#    environment:
#      - DB_USER=redmine
#      - DB_PASS=password
#      - DB_NAME=redmine_production
#    volumes:
#      - /srv/docker/redmine/postgresql:/var/lib/postgresql
#    healthcheck:
#      test: "psql -U postgres"
#      interval: 3s
#      timeout: 3s
#      retries: 5
#      start_period: 10s
  redmine:
    build: ./
    image: redmine:5.0.5
    environment:
      - TZ=Asia/Ho_Chi_minh

      - DB_ADAPTER=mysql2
      - DB_HOST=192.168.45.52
      - DB_PORT=19202
      - DB_USER=redmine
      - DB_PASS=UnGfAeU75QE2Jx
      - DB_NAME=nex-redmine-v2
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:3000"
    volumes:
      - ./data/redmine:/home/redmine/data
      - ./data/redmine-logs:/var/log/redmine
