# Bản build 19/09/2023 dùng resource của chính redmine
version: '3.1'
services:
  redmine:
    image: redmine:5.0-alpine
    environment:
      REDMINE_DB_MYSQL: 192.168.0.1
      REDMINE_DB_PORT: 92012
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8
      REDMINE_SECRET_KEY_BASE: supersecretkey
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/themes
      - ./redmine/images:/usr/src/redmine/public/images
