# Bản build 19/09/2023 dùng resource của chính redmine
version: '3.1'
services:
  redmine:
    image: redmine:4.2.10-bullseye
    environment:
      REDMINE_DB_MYSQL: 192.168.1.11
      REDMINE_DB_PORT: 33066
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: caimaydao234
      REDMINE_DB_ENCODING: utf8
      REDMINE_SECRET_KEY_BASE: supersecretkey
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./red42/files:/usr/src/redmine/files
      - ./red42/plugins:/usr/src/redmine/plugins
      - ./red42/themes:/usr/src/redmine/themes
